# Generated by Django 5.2.1 on 2025-10-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryrequest',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='categoryrequest',
            name='processed_by',
        ),
        migrations.RemoveField(
            model_name='categoryrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryRequest',
        ),
    ]
