# Generated by Django 5.2.6 on 2025-09-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
