# Generated by Django 5.2.1 on 2025-09-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локація', 'verbose_name_plural': 'Локації'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
    ]
