# Generated by Django 5.2.1 on 2025-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0002_alter_location_options_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
