# Generated by Django 5.2.1 on 2025-10-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0002_alter_location_options_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('promo_type', models.CharField(choices=[('balance', 'Поповнення балансу'), ('discount', 'Знижка на замовлення'), ('free_item', 'Безкоштовний товар/велика знижка')], max_length=20, verbose_name='Тип промокоду')),
                ('value', models.DecimalField(decimal_places=2, help_text='Сума поповнення або відсоток знижки', max_digits=10, verbose_name='Значення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Максимум використань')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Використано разів')),
                ('valid_from', models.DateTimeField(verbose_name='Діє з')),
                ('valid_to', models.DateTimeField(verbose_name='Діє до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('target_category', models.ForeignKey(blank=True, help_text="Категорія товарів, на які діє промокод (для типу 'Безкоштовний товар')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='bns_goiteens.category', verbose_name='Цільова категорія')),
                ('target_item', models.ForeignKey(blank=True, help_text="Товар, на який діє промокод (для типу 'Безкоштовний товар')", null=True, on_delete=django.db.models.deletion.SET_NULL, to='bns_goiteens.item', verbose_name='Цільовий товар')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
            },
        ),
    ]
