# Generated by Django 5.2.1 on 2025-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0002_alter_user_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
