# Generated by Django 5.2.1 on 2025-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0002_alter_location_options_alter_rating_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
