# Generated by Django 5.2.1 on 2025-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0005_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='lat',
            field=models.FloatField(default=50.4501),
        ),
        migrations.AddField(
            model_name='map',
            name='lng',
            field=models.FloatField(default=30.5234),
        ),
    ]
