# Generated by Django 5.2.1 on 2025-10-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0005_alter_comment_author_alter_comment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.PositiveIntegerField(null=True, verbose_name='Перегляди'),
        ),
    ]
