# Generated by Django 5.2.1 on 2025-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0007_alter_category_options_remove_category_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='items_image/default.png', null=True, upload_to='items_image/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='items_image/default.png', null=True, upload_to='items_image/'),
        ),
    ]
