# Generated by Django 5.2.1 on 2025-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0008_alter_item_image_alter_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
