# Generated by Django 5.2.1 on 2025-10-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0010_complaint'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bns_complaints', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(),
        ),

    ]
