# Generated by Django 5.2.1 on 2025-10-17 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bns_goiteens', '0011_message_room_name_user_balance_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reason',
            field=models.CharField(choices=[('swearing', 'Образи / мова ненависті'), ('spam', 'Спам'), ('harassment', 'Переслідування'), ('inappropriate', 'Неприпустимий контент'), ('other', 'Інше')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),

    ]
